// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEXf99OczhnTCLk6uMoZYtsrpnqya_Baw',
    appId: '1:712083908730:web:db2c00eaab6a69591d33c3',
    messagingSenderId: '712083908730',
    projectId: 'task-management-1809',
    authDomain: 'task-management-1809.firebaseapp.com',
    storageBucket: 'task-management-1809.appspot.com',
    measurementId: 'G-XS2X3W9CH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0gVwwAHhCYfRHKFG6NhuXa9_DVkLSv3U',
    appId: '1:712083908730:android:0c75e482ab6d5a461d33c3',
    messagingSenderId: '712083908730',
    projectId: 'task-management-1809',
    storageBucket: 'task-management-1809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB12zOOiMoSWK6rUztHKu-DZvBBXThdI-M',
    appId: '1:712083908730:ios:30ac875c97341b361d33c3',
    messagingSenderId: '712083908730',
    projectId: 'task-management-1809',
    storageBucket: 'task-management-1809.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB12zOOiMoSWK6rUztHKu-DZvBBXThdI-M',
    appId: '1:712083908730:ios:30ac875c97341b361d33c3',
    messagingSenderId: '712083908730',
    projectId: 'task-management-1809',
    storageBucket: 'task-management-1809.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEXf99OczhnTCLk6uMoZYtsrpnqya_Baw',
    appId: '1:712083908730:web:bc2905cd00d40f0b1d33c3',
    messagingSenderId: '712083908730',
    projectId: 'task-management-1809',
    authDomain: 'task-management-1809.firebaseapp.com',
    storageBucket: 'task-management-1809.appspot.com',
    measurementId: 'G-BQW98F4L90',
  );
}
